### ISSUE TITLE
Cannot read properpty webpackconfig of undefined

### ISSUE THREAD

**Issue by josegus** [omnichronous/multimix#4]
Following your package.json scripts, when i run npm run watch it gives me the following error:

0 info it worked if it ends with ok
1 verbose cli [ '/home/jose/.nvm/versions/node/v10.14.1/bin/node',
1 verbose cli   '/home/jose/.nvm/versions/node/v10.14.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'watch' ]
2 info using npm@6.4.1
3 info using node@v10.14.1
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle @~prewatch: @
6 info lifecycle @~watch: @
7 verbose lifecycle @~watch: unsafe-perm in lifecycle true
8 verbose lifecycle @~watch: PATH: /home/jose/.nvm/versions/node/v10.14.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/marketplace/node_modules/.bin:/home/jose/.nvm/versions/node/v10.14.1/bin:/home/jose/bin:/home/jose/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/jose/.composer/vendor/bin
9 verbose lifecycle @~watch: CWD: /var/www/marketplace
10 silly lifecycle @~watch: Args: [ '-c', 'npm run development -- --watch' ]
11 silly lifecycle @~watch: Returned: code: 1  signal: null
12 info lifecycle @~watch: Failed to exec watch script
13 verbose stack Error: @ watch: `npm run development -- --watch`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/jose/.nvm/versions/node/v10.14.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/jose/.nvm/versions/node/v10.14.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid @
15 verbose cwd /var/www/marketplace
16 verbose Linux 4.15.0-76-generic
17 verbose argv "/home/jose/.nvm/versions/node/v10.14.1/bin/node" "/home/jose/.nvm/versions/node/v10.14.1/bin/npm" "run" "watch"
18 verbose node v10.14.1
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error @ watch: `npm run development -- --watch`
22 error Exit status 1
23 error Failed at the @ watch script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by josegus** [comment]
Found the error: do not use:

let { mix } = require('mix');

use:

let mix = require('mix');
